<?php
/** @var \Brituy\SimpleBlog\Block\Article\View $block */
/** $article = $block->getArticle(); */
$format = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
$currentAuthor = $block->getAuthor();
?>

<?php foreach ($block->getArticle() as $article): ?>
<div class="blog-detail-title">
    <h1><?php echo $article->getTitle() ?></h1>
    <ul class="blog-article-info">
        <li>
            <div class="author-link">
                <?php echo __('By ') ?>
                <?php foreach ($currentAuthor as $currentAuthor): ?>
                <a href="<?php echo $currentAuthor->getData('author_mail') ?>"
                   title="<?php echo $currentAuthor->getData('author_mail') ?>">
                    <span><?php echo $currentAuthor->getData('author') ?></span>
                </a>
                <?php endforeach; ?>
            </div>
        </li>
        <li class="article-date"><?php echo $block->formatDate($article->getBlogDate(), $format) ?></li>
    </ul>
    <div class="blog-content">
        <?php echo $article->getContent(); ?>
    </div>
    <?php endforeach; ?>
</div>
