<?php
/** @var $block \Brituy\SimpleBlog\Block\BlogList */
$format = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
$articles = $block->getArticles();
$configUrl = $block->getBaseUrlConfig();
?>

<?php if (!$articles->count()): ?>
    <div class="message info empty">
        <div>
            <?php echo __('We can\'t find posts matching the selection.') ?>
        </div>
    </div>
<?php else: ?>
<h1><?php echo __('Latest Blog Articles') ?></h1>
<ul class="blog-articles-list">
    <?php /** @var $article \Brituy\SimpleBlog\Model\Blog */ ?>
    <?php foreach ($block->getArticles() as $article): ?>
        <li class="blog-articles-list-item">
            <h3 class="blog-articles-item-title">
                <a href="<?php echo $block->getUrl('simpleblog/index/view',['blog_id'=>$article->getBlogId()]) ?>"><?php echo $article->getTitle() ?></a>
            </h3>

            <div class="blog-articles-item-content">
                <?php echo mb_substr($article->getContent(), 0, 150).' ... '?>
                <a href="<?php echo $block->getUrl('simpleblog/index/view',['blog_id'=>$article->getBlogId()]) ?>">read more</a>
            </div>

            <div class="blog-articles-item-meta">
                <strong><?php echo __('Article date:') ?></strong> <?php echo $block->formatDate($article->getBlogDate(), $format) ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
<?php if ($block->getPagerHtml()): ?>
        <div class="toolbar-bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
<?php endif; ?>
