<!-- Call data from mageplaza_helloworld_post table via method getPostCollection -->

<?php

/**
 * @var \Brituy\SimpleBlog\Block\Display $block
 */

echo $block->sayHello();

?>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}

</style>

<table>
  <tr>
    <th class="blog-id">Id</th>
    <th class="visibility">Visible</th>
    <th class="blog_date">Date</th>
    <th class="title">Title</th>
    <th class="content">Content</th>
  </tr>
    <?php
        foreach ($block->getPostCollection() as $key=>$post)
        {
            echo '<tr>
                    <td>'.$post->getBlogId().'</td>
                    <td>'.$post->getVisibility().'</td>
                    <td>'.$post->getBlogDate().'</td>
                    <td>'.$post->getTitle().'</td>
                    <td>'.$post->getContent().'</td>
                  </tr>';
        }
    ?>
</table>

</body>
</html>
