<?php
/** sidebar categories template */
?>

<?php
    $blogCategories = $block->getCategories();
    $selectedCategory = $block->getSelectedCategory();
    $configUrl = $block->getBaseUrlConfig();
?>

    <?php if ($blogCategories): ?>
        <p><strong><?php echo __('Blog categories:') ?></strong></p>
        <div class="categories-grid">
            <ul class="categories-items">
                <?php foreach ($blogCategories as $blogCategories):?>
                    <li class="categories-item">
                        <?php $currentCategoryId = $blogCategories->getCategoryId(); ?>
                        <?php if ($currentCategoryId==$selectedCategory): ?>
                            <a class="categories-item-link-sel" href="<?php echo $block->getUrl('simpleblog',['category_id'=>$currentCategoryId]) ?>">
                                <span class="categories-title">
                                    <?php $ArticlesCount = $block->getArticlesCount($currentCategoryId); ?>
                                    <strong><?php echo $blogCategories->getCategory().' ('.$ArticlesCount.')' ?></strong>
                                </span>
                            </a>
                        <?php else: ?>
                            <a class="categories-item-link" href="<?php echo $block->getUrl('simpleblog',['category_id'=>$currentCategoryId]) ?>">
                                <span class="categories-title">
                                    <?php $ArticlesCount = $block->getArticlesCount($currentCategoryId); ?>
                                    <?php echo $blogCategories->getCategory().' ('.$ArticlesCount.')' ?>
                                </span>
                            </a>
                        <?php endif; ?>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    <?php endif;?>
